"""Canonical manuscript data for the arXiv paper package.

This module provides a single source of truth for the manuscript package in
repo snapshots where the full `outputs/` experiment tree is not available.
The paper asset generator materializes lightweight summary CSV files under
`outputs/summary_tables/` from these values and then reads those CSV files to
build the LaTeX tables and figures.
"""

from __future__ import annotations

from typing import Final


TITLE: Final[str] = (
    "Uncertainty-Aware Last-Layer Adaptation of RETFound for Referable "
    "Diabetic Retinopathy Screening Under Dataset Shift"
)
AUTHOR: Final[str] = "Karim Mardhani"
AFFILIATION: Final[str] = (
    "Master of Science in Artificial Intelligence\\\\"
    "University of Colorado Boulder\\\\"
    "Boulder, CO, USA"
)
EMAIL: Final[str] = "Karim.Mardhani@colorado.edu"
REPOSITORY_URL: Final[str] = "https://github.com/kmardhani/uncertainty-aware-retfound"
COMMIT_HASH: Final[str] = "b7e579b183eda54e99d5d3944574fac7dca9d322"
ARXIV_PRIMARY: Final[str] = "cs.CV"
ARXIV_SECONDARY: Final[str] = "cs.LG"


DATASET_SUMMARY: Final[list[dict[str, object]]] = [
    {
        "dataset": "APTOS 2019",
        "total_images": 3662,
        "diagnosis_counts": "0=1805, 1=370, 2=999, 3=193, 4=295",
        "binary_mapping": "0/1 -> non-ref, 2/3/4 -> ref",
        "non_referable": 2175,
        "referable": 1487,
        "train_count": 2930,
        "val_count": 366,
        "test_count": 366,
        "train_labels": "1734 / 1196",
        "val_labels": "212 / 154",
        "test_labels": "229 / 137",
    },
    {
        "dataset": "DDR",
        "total_images": 12522,
        "diagnosis_counts": "0=6266, 1=630, 2=4477, 3=236, 4=913",
        "binary_mapping": "0/1 -> non-ref, 2/3/4 -> ref",
        "non_referable": 6896,
        "referable": 5626,
        "train_count": 8765,
        "val_count": 1878,
        "test_count": 1879,
        "train_labels": "4827 / 3938",
        "val_labels": "1034 / 844",
        "test_labels": "1035 / 844",
    },
]


FEATURE_EXTRACTION_SUMMARY: Final[list[dict[str, object]]] = [
    {
        "dataset": "APTOS 2019",
        "backbone": "RETFound_mae",
        "checkpoint": "RETFound_mae_natureCFP.pth",
        "feature_dim": 1024,
        "resize": 224,
        "center_crop": 224,
        "device": "cuda",
        "batch_size": 8,
    },
    {
        "dataset": "DDR",
        "backbone": "RETFound_mae",
        "checkpoint": "RETFound_mae_natureCFP.pth",
        "feature_dim": 1024,
        "resize": 224,
        "center_crop": 224,
        "device": "cuda",
        "batch_size": 16,
    },
]


MODEL_COMPARISON_ROWS: Final[list[dict[str, object]]] = [
    {
        "model": "cached_softmax",
        "dataset": "APTOS",
        "source_path": "outputs/feature_heads/retfound_softmax_linear_5epoch_bs8/metrics.json",
        "coverage": 1.0,
        "deferred_count": 0,
        "referral_rate": 0.0,
        "positive_prediction_rate": 164 / 366,
        "accuracy": 0.8798,
        "auc": 0.9580,
        "sensitivity": 0.8896,
        "specificity": 0.8726,
        "balanced_accuracy": 0.8811,
        "ece": 0.0348,
        "nll": 0.2643,
        "brier": 0.0807,
        "false_positives": 27,
        "false_negatives": 17,
    },
    {
        "model": "cached_softmax_temperature_scaled",
        "dataset": "APTOS",
        "source_path": "outputs/feature_heads/retfound_softmax_linear_5epoch_bs8/temperature_scaling.json",
        "coverage": 1.0,
        "deferred_count": 0,
        "referral_rate": 0.0,
        "positive_prediction_rate": 164 / 366,
        "accuracy": 0.8798,
        "auc": 0.9580,
        "sensitivity": 0.8896,
        "specificity": 0.8726,
        "balanced_accuracy": 0.8811,
        "ece": 0.0186,
        "nll": 0.2558,
        "brier": 0.0798,
        "false_positives": 27,
        "false_negatives": 17,
    },
    {
        "model": "variational_bayesian_val_loss_selected",
        "dataset": "APTOS",
        "source_path": "outputs/feature_heads/retfound_variational_bayesian_20epoch_best_val_loss/best_metrics.json",
        "coverage": 1.0,
        "deferred_count": 0,
        "referral_rate": 0.0,
        "positive_prediction_rate": 157 / 366,
        "accuracy": 0.8934,
        "auc": 0.9650,
        "sensitivity": 0.8831,
        "specificity": 0.9009,
        "balanced_accuracy": 0.8920,
        "ece": 0.0216,
        "nll": 0.2371,
        "brier": 0.0724,
        "false_positives": 21,
        "false_negatives": 18,
    },
    {
        "model": "variational_bayesian_max_sensitivity_sweep",
        "dataset": "APTOS",
        "source_path": "outputs/feature_heads/sweeps/bayes_sensitivity_kl_0.001_prior_2.0/best_metrics.json",
        "coverage": 1.0,
        "deferred_count": 0,
        "referral_rate": 0.0,
        "positive_prediction_rate": 181 / 366,
        "accuracy": 0.8934,
        "auc": 0.9613,
        "sensitivity": 0.9610,
        "specificity": 0.8443,
        "balanced_accuracy": 0.9027,
        "ece": 0.0320,
        "nll": 0.2794,
        "brier": 0.0842,
        "false_positives": 33,
        "false_negatives": 6,
    },
    {
        "model": "variational_bayesian_balanced_sweep",
        "dataset": "APTOS",
        "source_path": "outputs/feature_heads/sweeps/bayes_sensitivity_kl_0.00003_prior_2.0/best_metrics.json",
        "coverage": 1.0,
        "deferred_count": 0,
        "referral_rate": 0.0,
        "positive_prediction_rate": 176 / 366,
        "accuracy": 0.9016,
        "auc": 0.9617,
        "sensitivity": 0.9545,
        "specificity": 0.8632,
        "balanced_accuracy": 0.9089,
        "ece": 0.0275,
        "nll": 0.2639,
        "brier": 0.0796,
        "false_positives": 29,
        "false_negatives": 7,
    },
    {
        "model": "laplace_val_loss_selected",
        "dataset": "APTOS",
        "source_path": "outputs/feature_heads/retfound_laplace_20epoch_best_val_loss/best_metrics.json",
        "coverage": 1.0,
        "deferred_count": 0,
        "referral_rate": 0.0,
        "positive_prediction_rate": 150 / 366,
        "accuracy": 0.8962,
        "auc": 0.9666,
        "sensitivity": 0.8636,
        "specificity": 0.9198,
        "balanced_accuracy": 0.8917,
        "ece": 0.0972,
        "nll": 0.2891,
        "brier": 0.0826,
        "false_positives": 17,
        "false_negatives": 21,
    },
    {
        "model": "laplace_sensitivity_selected",
        "dataset": "APTOS",
        "source_path": "outputs/feature_heads/sweeps/laplace_sensitivity_prior_precision_10.0/best_metrics.json",
        "coverage": 1.0,
        "deferred_count": 0,
        "referral_rate": 0.0,
        "positive_prediction_rate": 176 / 366,
        "accuracy": 0.8962,
        "auc": 0.9586,
        "sensitivity": 0.9481,
        "specificity": 0.8585,
        "balanced_accuracy": 0.9033,
        "ece": 0.0900,
        "nll": 0.3061,
        "brier": 0.0894,
        "false_positives": 30,
        "false_negatives": 8,
    },
    {
        "model": "sngp_val_loss_selected",
        "dataset": "APTOS",
        "source_path": "outputs/feature_heads/aptos2019_retfound_sngp_val_loss/best_metrics.json",
        "coverage": 1.0,
        "deferred_count": 0,
        "referral_rate": 0.0,
        "positive_prediction_rate": 152 / 366,
        "accuracy": 0.9071,
        "auc": 0.9756,
        "sensitivity": 0.8831,
        "specificity": 0.9245,
        "balanced_accuracy": 0.9038,
        "ece": 0.0288,
        "nll": None,
        "brier": None,
        "false_positives": 16,
        "false_negatives": 18,
    },
    {
        "model": "sngp_sensitivity_selected",
        "dataset": "APTOS",
        "source_path": "outputs/feature_heads/aptos2019_retfound_sngp_sensitivity/best_metrics.json",
        "coverage": 1.0,
        "deferred_count": 0,
        "referral_rate": 0.0,
        "positive_prediction_rate": 181 / 366,
        "accuracy": 0.9098,
        "auc": 0.9711,
        "sensitivity": 0.9805,
        "specificity": 0.8585,
        "balanced_accuracy": 0.9195,
        "ece": 0.0287,
        "nll": None,
        "brier": None,
        "false_positives": 30,
        "false_negatives": 3,
    },
    {
        "model": "ddr_softmax",
        "dataset": "DDR",
        "source_path": "outputs/feature_heads/ddr_retfound_softmax_linear_10epoch_bs16/metrics.json",
        "coverage": 1.0,
        "deferred_count": 0,
        "referral_rate": 0.0,
        "positive_prediction_rate": 855 / 1878,
        "accuracy": 0.7939,
        "auc": 0.8688,
        "sensitivity": 0.7773,
        "specificity": 0.8075,
        "balanced_accuracy": 0.7924,
        "ece": 0.0223,
        "nll": 0.4504,
        "brier": 0.1472,
        "false_positives": 199,
        "false_negatives": 188,
    },
    {
        "model": "ddr_bayesian_val_loss_selected",
        "dataset": "DDR",
        "source_path": "outputs/feature_heads/ddr_retfound_variational_bayesian_20epoch_best_val_loss/best_metrics.json",
        "coverage": 1.0,
        "deferred_count": 0,
        "referral_rate": 0.0,
        "positive_prediction_rate": 766 / 1878,
        "accuracy": 0.7966,
        "auc": 0.8782,
        "sensitivity": 0.7275,
        "specificity": 0.8530,
        "balanced_accuracy": 0.7902,
        "ece": 0.0174,
        "nll": 0.4357,
        "brier": 0.1420,
        "false_positives": 152,
        "false_negatives": 230,
    },
    {
        "model": "ddr_bayesian_sensitivity_selected",
        "dataset": "DDR",
        "source_path": "outputs/feature_heads/ddr_retfound_variational_bayesian_20epoch_best_sensitivity/best_metrics.json",
        "coverage": 1.0,
        "deferred_count": 0,
        "referral_rate": 0.0,
        "positive_prediction_rate": 1022 / 1878,
        "accuracy": 0.7678,
        "auc": 0.8634,
        "sensitivity": 0.8472,
        "specificity": 0.7031,
        "balanced_accuracy": 0.7751,
        "ece": 0.0097,
        "nll": 0.4776,
        "brier": 0.1567,
        "false_positives": 307,
        "false_negatives": 129,
    },
    {
        "model": "ddr_from_aptos_sngp_sensitivity",
        "dataset": "DDR",
        "source_path": "outputs/feature_heads/ddr_from_aptos_sngp_sensitivity/metrics.json",
        "coverage": 1.0,
        "deferred_count": 0,
        "referral_rate": 0.0,
        "positive_prediction_rate": 365 / 1878,
        "accuracy": 0.5990,
        "auc": 0.5833,
        "sensitivity": 0.2701,
        "specificity": 0.8675,
        "balanced_accuracy": 0.5688,
        "ece": 0.2168,
        "nll": 0.9340,
        "brier": 0.2977,
        "false_positives": 137,
        "false_negatives": 616,
    },
]


THRESHOLD_SWEEP_ROWS: Final[list[dict[str, object]]] = [
    {
        "sweep_name": "ddr_softmax_temp",
        "source_path": "outputs/threshold_sweeps/ddr/softmax_temp_threshold_sweep.csv",
        "selected_policy": "best_balanced_accuracy",
        "threshold": 0.50,
        "accuracy": 0.7939,
        "sensitivity": 0.7773,
        "specificity": 0.8075,
        "balanced_accuracy": 0.7924,
        "false_negatives": 188,
        "false_positives": 199,
    },
    {
        "sweep_name": "ddr_softmax_temp",
        "source_path": "outputs/threshold_sweeps/ddr/softmax_temp_threshold_sweep.csv",
        "selected_policy": "lowest_false_negatives",
        "threshold": 0.03,
        "accuracy": 0.5059,
        "sensitivity": 1.0000,
        "specificity": 0.1025,
        "balanced_accuracy": 0.5512,
        "false_negatives": 0,
        "false_positives": 928,
    },
    {
        "sweep_name": "ddr_bayes_val_loss",
        "source_path": "outputs/threshold_sweeps/ddr/bayesian_val_loss_threshold_sweep.csv",
        "selected_policy": "best_balanced_accuracy",
        "threshold": 0.40,
        "accuracy": 0.7929,
        "sensitivity": 0.8104,
        "specificity": 0.7785,
        "balanced_accuracy": 0.7945,
        "false_negatives": 160,
        "false_positives": 229,
    },
    {
        "sweep_name": "ddr_bayes_sensitivity",
        "source_path": "outputs/threshold_sweeps/ddr/bayesian_sensitivity_threshold_sweep.csv",
        "selected_policy": "best_balanced_accuracy",
        "threshold": 0.55,
        "accuracy": 0.7806,
        "sensitivity": 0.8152,
        "specificity": 0.7524,
        "balanced_accuracy": 0.7838,
        "false_negatives": 156,
        "false_positives": 256,
    },
    {
        "sweep_name": "ddr_bayes_sensitivity",
        "source_path": "outputs/threshold_sweeps/ddr/bayesian_sensitivity_threshold_sweep.csv",
        "selected_policy": "lowest_false_negatives",
        "threshold": 0.03,
        "accuracy": 0.4787,
        "sensitivity": 1.0000,
        "specificity": 0.0532,
        "balanced_accuracy": 0.5266,
        "false_negatives": 0,
        "false_positives": 979,
    },
    {
        "sweep_name": "ddr_from_aptos_sngp",
        "source_path": "outputs/threshold_sweeps/ddr_from_aptos_sngp_sensitivity/threshold_sweep.csv",
        "selected_policy": "best_balanced_accuracy",
        "threshold": 0.45,
        "accuracy": 0.6017,
        "sensitivity": 0.3069,
        "specificity": 0.8424,
        "balanced_accuracy": 0.5746,
        "false_negatives": 585,
        "false_positives": 163,
    },
    {
        "sweep_name": "ddr_from_aptos_sngp",
        "source_path": "outputs/threshold_sweeps/ddr_from_aptos_sngp_sensitivity/threshold_sweep.csv",
        "selected_policy": "lowest_false_negatives",
        "threshold": 0.01,
        "accuracy": 0.4526,
        "sensitivity": 0.9882,
        "specificity": 0.0155,
        "balanced_accuracy": 0.5018,
        "false_negatives": 10,
        "false_positives": 1018,
    },
]


SELECTIVE_REFERRAL_ROWS: Final[list[dict[str, object]]] = [
    {
        "run_name": "aptos2019_sngp_sensitivity_entropy",
        "uncertainty_column": "predictive_entropy",
        "source_path": "outputs/selective_referral/aptos2019_sngp_sensitivity_entropy/selective_referral.csv",
        "target_coverage": 0.80,
        "coverage": 0.8005,
        "deferred_count": 73,
        "accepted_count": 293,
        "accuracy": 0.9522,
        "sensitivity": 1.0000,
        "specificity": 0.9146,
        "balanced_accuracy": 0.9573,
        "false_positives": 14,
        "false_negatives": 0,
        "referral_rate": 0.1995,
    },
    {
        "run_name": "aptos2019_sngp_sensitivity_variance",
        "uncertainty_column": "sngp_variance",
        "source_path": "outputs/selective_referral/aptos2019_sngp_sensitivity_variance/selective_referral.csv",
        "target_coverage": 0.80,
        "coverage": 0.8005,
        "deferred_count": 73,
        "accepted_count": 293,
        "accuracy": 0.8874,
        "sensitivity": 0.9732,
        "specificity": 0.8343,
        "balanced_accuracy": 0.9038,
        "false_positives": 30,
        "false_negatives": 3,
        "referral_rate": 0.1995,
    },
    {
        "run_name": "aptos2019_sngp_sensitivity_sngp_uncertainty",
        "uncertainty_column": "sngp_uncertainty",
        "source_path": "outputs/selective_referral/aptos2019_sngp_sensitivity_sngp_uncertainty/selective_referral.csv",
        "target_coverage": 0.80,
        "coverage": 0.8005,
        "deferred_count": 73,
        "accepted_count": 293,
        "accuracy": 0.9488,
        "sensitivity": 0.9924,
        "specificity": 0.9136,
        "balanced_accuracy": 0.9530,
        "false_positives": 14,
        "false_negatives": 1,
        "referral_rate": 0.1995,
    },
    {
        "run_name": "ddr_bayesian_sensitivity_confidence",
        "uncertainty_column": "confidence",
        "source_path": "outputs/selective_referral/ddr/bayesian_confidence.csv",
        "target_coverage": 0.80,
        "coverage": 0.8003,
        "deferred_count": 375,
        "accepted_count": 1503,
        "accuracy": 0.8230,
        "sensitivity": 0.8966,
        "specificity": 0.7596,
        "balanced_accuracy": 0.8281,
        "false_positives": 194,
        "false_negatives": 72,
        "referral_rate": 0.1997,
    },
    {
        "run_name": "ddr_bayesian_sensitivity_predictive_entropy",
        "uncertainty_column": "predictive_entropy",
        "source_path": "outputs/selective_referral/ddr/bayesian_predictive_entropy.csv",
        "target_coverage": 0.80,
        "coverage": 0.8003,
        "deferred_count": 375,
        "accepted_count": 1503,
        "accuracy": 0.8230,
        "sensitivity": 0.8966,
        "specificity": 0.7596,
        "balanced_accuracy": 0.8281,
        "false_positives": 194,
        "false_negatives": 72,
        "referral_rate": 0.1997,
    },
    {
        "run_name": "ddr_bayesian_sensitivity_probability_variance",
        "uncertainty_column": "probability_variance",
        "source_path": "outputs/selective_referral/ddr/bayesian_probability_variance.csv",
        "target_coverage": 0.80,
        "coverage": 0.8003,
        "deferred_count": 375,
        "accepted_count": 1503,
        "accuracy": 0.8011,
        "sensitivity": 0.8887,
        "specificity": 0.7298,
        "balanced_accuracy": 0.8093,
        "false_positives": 224,
        "false_negatives": 75,
        "referral_rate": 0.1997,
    },
    {
        "run_name": "ddr_bayesian_sensitivity_mutual_information",
        "uncertainty_column": "mutual_information",
        "source_path": "outputs/selective_referral/ddr/bayesian_mutual_information.csv",
        "target_coverage": 0.80,
        "coverage": 0.8003,
        "deferred_count": 375,
        "accepted_count": 1503,
        "accuracy": 0.7964,
        "sensitivity": 0.8783,
        "specificity": 0.7284,
        "balanced_accuracy": 0.8033,
        "false_positives": 223,
        "false_negatives": 83,
        "referral_rate": 0.1997,
    },
    {
        "run_name": "ddr_from_aptos_sngp_sensitivity_entropy",
        "uncertainty_column": "predictive_entropy",
        "source_path": "outputs/selective_referral/ddr_from_aptos_sngp_sensitivity_entropy/selective_referral.csv",
        "target_coverage": 0.80,
        "coverage": 0.8003,
        "deferred_count": 375,
        "accepted_count": 1503,
        "accuracy": 0.6154,
        "sensitivity": 0.2160,
        "specificity": 0.9298,
        "balanced_accuracy": 0.5729,
        "false_positives": 59,
        "false_negatives": 519,
        "referral_rate": 0.1997,
    },
    {
        "run_name": "ddr_from_aptos_sngp_sensitivity_variance",
        "uncertainty_column": "sngp_variance",
        "source_path": "outputs/selective_referral/ddr_from_aptos_sngp_sensitivity_variance/selective_referral.csv",
        "target_coverage": 0.80,
        "coverage": 0.8003,
        "deferred_count": 375,
        "accepted_count": 1503,
        "accuracy": 0.5935,
        "sensitivity": 0.3042,
        "specificity": 0.8370,
        "balanced_accuracy": 0.5706,
        "false_positives": 133,
        "false_negatives": 478,
        "referral_rate": 0.1997,
    },
    {
        "run_name": "ddr_from_aptos_sngp_sensitivity_sngp_uncertainty",
        "uncertainty_column": "sngp_uncertainty",
        "source_path": "outputs/selective_referral/ddr_from_aptos_sngp_sensitivity_sngp_uncertainty/selective_referral.csv",
        "target_coverage": 0.80,
        "coverage": 0.8003,
        "deferred_count": 375,
        "accepted_count": 1503,
        "accuracy": 0.6134,
        "sensitivity": 0.2165,
        "specificity": 0.9284,
        "balanced_accuracy": 0.5725,
        "false_positives": 60,
        "false_negatives": 521,
        "referral_rate": 0.1997,
    },
]


DECISION_POLICY_ROWS: Final[list[dict[str, object]]] = [
    {
        "policy": "model:softmax_temp",
        "accuracy": 0.8798,
        "sensitivity": 0.8896,
        "specificity": 0.8726,
        "false_positives": 27,
        "false_negatives": 17,
        "referral_rate": 0.0,
        "positive_prediction_rate": 164 / 366,
    },
    {
        "policy": "model:bayes_max_sensitivity",
        "accuracy": 0.8934,
        "sensitivity": 0.9610,
        "specificity": 0.8443,
        "false_positives": 33,
        "false_negatives": 6,
        "referral_rate": 0.0,
        "positive_prediction_rate": 181 / 366,
    },
    {
        "policy": "model:bayes_balanced",
        "accuracy": 0.9016,
        "sensitivity": 0.9545,
        "specificity": 0.8632,
        "false_positives": 29,
        "false_negatives": 7,
        "referral_rate": 0.0,
        "positive_prediction_rate": 176 / 366,
    },
    {
        "policy": "model:laplace_sensitivity",
        "accuracy": 0.8962,
        "sensitivity": 0.9481,
        "specificity": 0.8585,
        "false_positives": 30,
        "false_negatives": 8,
        "referral_rate": 0.0,
        "positive_prediction_rate": 176 / 366,
    },
    {
        "policy": "policy:or_rule",
        "accuracy": 0.8852,
        "sensitivity": 0.9610,
        "specificity": 0.8302,
        "false_positives": 36,
        "false_negatives": 6,
        "referral_rate": 0.0,
        "positive_prediction_rate": 184 / 366,
    },
    {
        "policy": "policy:majority_vote",
        "accuracy": 0.8934,
        "sensitivity": 0.9545,
        "specificity": 0.8491,
        "false_positives": 32,
        "false_negatives": 7,
        "referral_rate": 0.0,
        "positive_prediction_rate": 179 / 366,
    },
    {
        "policy": "policy:and_rule",
        "accuracy": 0.8907,
        "sensitivity": 0.8896,
        "specificity": 0.8915,
        "false_positives": 23,
        "false_negatives": 17,
        "referral_rate": 0.0,
        "positive_prediction_rate": 160 / 366,
    },
]

